# Create a new user
POST http://localhost:3333/api/comments/register HTTP/1.1
Content-Type: application/json

{
  "userId": "13123123451",
  "workerId": "3848345781",
  "taskId": "232312",
  "content": "it's good",
  "rating": "3"
}

###

# Get all comments for this user
GET http://localhost:3333/api/comments/3848345781 HTTP/1.1
Content-Type: application/json

###
